dist: xenial
sudo: false

language: node_js
node_js:
    - "11.0"

install:
    - npm install -g firebase-tools
    - npm install

script:
    - npm run build

deploy:
    provider: firebase
    token:
        secure: $FIREBASE_TOKEN
    project: "carpincullo"
    message: "Deploying..."
