dist: xenial
sudo: false

language: node_js
node_js:
    - "11.0"

branches:
    only:
        - master

install:
    - npm install -g firebase-tools
    - npm install

script:
    - npm run build

after_success:
    - firebase deploy --only hosting --token $FIREBASE_TOKEN

notifications:
    slack: $SLACK_NOTIFICATION_TOKEN
